### PR TITLE
feat: migrate zeebe's backup api from /backups to /backup-runtime

### LINKED ISSUE #616: Migrate zeebe's backup api from `/actuator/bacups` to `/actuator/backup-runtime`
See https://github.com/camunda/camunda/issues/24456 for reference

### PR DESCRIPTION
**Pull request by entangled90**
Updates the actuator endpoints to match https://github.com/camunda/camunda/issues/24456

closes #616

### CODE REVIEW

**Review by lenaschoenburg — APPROVED** [review]
Thanks!

**Comment by entangled90** [comment]
Should I change the path depending on the version number?

**Comment by lenaschoenburg** [comment]
As far as I know we have no automated tests so nothing should break. Detecting the right version would be fancy but I don't think it's strictly required.

**Comment by entangled90** [comment]
I see that all other opened PR fail with the same error, should I proceed with the merge?

**Comment by lenaschoenburg** [comment]
I'd say yes unless @Zelldon vetos.

**Comment by Zelldon** [comment]
> As far as I know we have no automated tests so nothing should break. Detecting the right version would be fancy but I don't think it's strictly required. 

Wouldnt the experiment itself break then?

**Comment by lenaschoenburg** [comment]
> Wouldnt the experiment itself break then?

Which experiment? I found none that made use of backups.

**Pull request merged**
