### PR TITLE
New Zbchaos cli

### PR DESCRIPTION
**Pull request by Zelldon**
> ### Motivation
> 
> Currently we have [several shell scripts](https://github.com/zeebe-io/zeebe-chaos/tree/master/chaos-workers/chaos-experiments/scripts) to execute chaos experiments with [chaostoolkit](https://chaostoolkit.org/). The scripts are currently working well, but the maintenance is rather hard, especially for people which might not familiar enough with bash.
> 
> This is the reason why we already migrated some of them to a [kotlin based chaos worker](https://github.com/zeebe-io/zeebe-chaos/tree/master/chaos-workers/chaos-worker). But we haven't done this for scripts which directly interact with the kubernetes API. The problem here is that we would need an executable cli to reference them also in the chaostoolkit experiments, to run it locally. Furthermore, the interaction with kubernetes in go, I would say, is easier/better.
>  

See #121 

## What the PR contains

- [x] Setup go mod project
- [x] Setup corba
   - [x] setup first command -v/--version or -h/--help
   - [x] Build first image
- [x] Add [kubernetes go client](https://github.com/kubernetes/client-go)
  - [x] Add simple command to see all zeebe pods
- [x] Add zeebe go client dependency
  - [x] find out how to connect to the cluster
    - [x] either via exec http://runkiss.blogspot.com/2020/07/how-to-execute-command-on-kubernetes.html
    - [x] or via port forward might be better
  - [x] add topology command -> zeebe go client status
- [x] Migrate one more complicated
  - [x] Kill leader for partition

### Details

```
$ ./zbchaos -h
A chaos experimenting toolkit for Zeebe.
    Perfect to inject some chaos into your brokers and gateways.

Usage:
  zbchaos [flags]
  zbchaos [command]

Available Commands:
  brokers     Print the name of the Zeebe broker pods
  completion  Generate the autocompletion script for the specified shell
  help        Help about any command
  terminate   Terminates a Zeebe broker
  topology    Print the Zeebe topology deployed in the current namespace

Flags:
  -h, --help   help for zbchaos

Use "zbchaos [command] --help" for more information about a command.
```

#### Get Brokers

```
./zbchaos brokers
Connecting to zell-helm-test
zell-helm-test-zeebe-0
zell-helm-test-zeebe-1
zell-helm-test-zeebe-2
```

#### Topology

```
$ ./zbchaos topology
Connecting to zell-helm-test
Successfully created port forwarding tunnel

Response topology, {
  "brokers":  [
    {
      "nodeId":  2,
      "host":  "zell-helm-test-zeebe-2.zell-helm-test-zeebe.zell-helm-test.svc.cluster.local",
      "port":  26501,
      "partitions":  [
        {
          "partitionId":  1,
          "role":  "FOLLOWER",
          "health":  "HEALTHY"
        },
        {
          "partitionId":  2,
          "role":  "LEADER",
          "health":  "HEALTHY"
        },
        {
          "partitionId":  3,
          "role":  "LEADER",
          "health":  "HEALTHY"
        }
      ],
      "version":  "1.4.0-SNAPSHOT"
    },
    {
      "nodeId":  1,
      "host":  "zell-helm-test-zeebe-1.zell-helm-test-zeebe.zell-helm-test.svc.cluster.local",
      "port":  26501,
      "partitions":  [
        {
          "partitionId":  1,
          "role":  "LEADER",
          "health":  "HEALTHY"
        },
        {
          "partitionId":  2,
          "role":  "FOLLOWER",
          "health":  "HEALTHY"
        },
        {
          "partitionId":  3,
          "role":  "FOLLOWER",
          "health":  "HEALTHY"
        }
      ],
      "version":  "1.4.0-SNAPSHOT"
    },
    {
      "nodeId":  0,
      "host":  "zell-helm-test-zeebe-0.zell-helm-test-zeebe.zell-helm-test.svc.cluster.local",
      "port":  26501,
      "partitions":  [
        {
          "partitionId":  1,
          "role":  "FOLLOWER",
          "health":  "HEALTHY"
        },
        {
          "partitionId":  2,
          "role":  "FOLLOWER",
          "health":  "HEALTHY"
        },
        {
          "partitionId":  3,
          "role":  "FOLLOWER",
          "health":  "HEALTHY"
        }
      ],
      "version":  "1.4.0-SNAPSHOT"
    }
  ],
  "clusterSize":  3,
  "partitionsCount":  3,
  "replicationFactor":  3,
  "gatewayVersion":  "1.4.0-SNAPSHOT"
}
```

### Terminate

Allows to terminate a broker based on the role on a certain partition, like Leader for partition.

```
$ ./zbchaos terminate --partitionId 3 --role LEADER
Connecting to zell-helm-test
Successfully created port forwarding tunnel

Deleted zell-helm-test-zeebe-2
[zell go-chaos-worker/ cluster: zeebe-cluster ns:zell-helm-test]$ kgpo
NAME                                            READY   STATUS      RESTARTS   AGE
ccsm-curator-27444765-7r4mg                     0/1     Completed   0          8m12s
elasticsearch-master-0                          1/1     Running     0          82m
elasticsearch-master-1                          1/1     Running     0          82m
elasticsearch-master-2                          1/1     Running     0          17h
zell-helm-test-operate-5dbbbcd96-8dtqc          1/1     Running     0          101m
zell-helm-test-tasklist-54785c895b-427rh        1/1     Running     0          8h
zell-helm-test-zeebe-0                          1/1     Running     0          15m
zell-helm-test-zeebe-1                          1/1     Running     0          66m
zell-helm-test-zeebe-2                          0/1     Pending     0          6s
zell-helm-test-zeebe-gateway-54bb98b485-82pvs   1/1     Running     0          82m
zell-helm-test-zeebe-gateway-54bb98b485-hf8jq   1/1     Running     0          101m
zell-helm-test-zeebe-gateway-54bb98b485-wxrnn   1/1     Running     0          7h40m
```

### Future work

With that we can start to migrate more and more shell scripts. It allows to be used as chaos worker in testbench but also for "local" chaos experiments/runs. The cli can be referenced it in chaos toolkit experiments.

@npepinpe let me know what you think about that :) If you think it makes sense I would like to spent more time on this, also to add tests and ci etc.

### CODE REVIEW

**Comment by npepinpe** [comment]
If I understand, this would replace the existing shell scripts?

**Comment by Zelldon** [comment]
This is the plan yes :) If you agree with it @npepinpe

**Comment by Zelldon** [comment]
@npepinpe wants to check what our plan regarding other language support and will come back to it.

**Comment by npepinpe** [comment]
Like I said, I would like to make sure we're on the same page with the end goal. I think we are, but just to be on the safe side... :slightly_smiling_face: 

If I understand correctly, ultimately, the goal is to replace the Kotlin and Bash code entirely with Go code. There is a single binary which is the entry point for workers, which can then interact with K8S, Docker, etc., and Zeebe.

Golang is a good language of choice as the official APIs for K8S, Docker, etc., are all in Go. It's also a good way for us to dog feed the Zeebe Go client.

With that in mind, I think it's a good move, and I'm happy to push for it.

**Review by npepinpe — COMMENTED** [review]
It's generally good. One thing I would like to see, however, is splitting the CLI shell away from the core logic. By this I mean, leaving only the CLI specific code in the CLI module, and having the rest of the code as simple packages. Mostly this helps us split concern, but it also makes testing much easier.

I think you already mostly did that, except maybe the terminate command, which has a little bit more logic than I would expect.

Eventually we would also need tests, of course :smile: I would propose to start early, as then every PR can just add the required tests, as otherwise it just builds up debt.

**Comment by Zelldon** [comment]
Thanks @npepinpe really appreciate that and happy about the outcome :tada:

> If I understand correctly, ultimately, the goal is to replace the Kotlin and Bash code entirely with Go code. There is a single binary which is the entry point for workers, which can then interact with K8S, Docker, etc., and Zeebe.

First my idea was to just replace the scripts, but yes it makes totally sense then to completely replace the kotlin worker, since this is just also an attempt to replace some scipts. With the go worker it would be easier to also insert it into the chaos experiments (chaostoolkit).

> Golang is a good language of choice as the official APIs for K8S, Docker, etc., are all in Go. It's also a good way for us to dog feed the Zeebe Go client.

Exactly :muscle: :+1: 

> With that in mind, I think it's a good move, and I'm happy to push for it.

Love it :heart_eyes: 

Regarding the comment here https://github.com/zeebe-io/zeebe-chaos/pull/122#pullrequestreview-914089812 

I totally agree with your points, I just wanted to kept the work minimal for the first draft, and wanted to check whether it works and hear your opinion first.

I would like to merge this PR as first starting point, and then when can decide next week (hopefully) that I will work on this. Afterwards I would start creating some follow up issues (+epic issue). This would include setting up infrastructure, tests, general architecture, adjustment of experiments, etc. After creating such plan, I would go over to start with the first required steps and then implement and replace more of the scripts.

**Comment by Zelldon** [comment]
@npepinpe I will go with these changes and will iteratively more, like ci, tests and more features.

**Comment by npepinpe** [comment]
Relying on this before having tests raises the bar to onboard others, I think, so I'm not sure about it. Then again, there aren't many tests already :shrug:

**Comment by Zelldon** [comment]
We have now a go CI that checks:

- licenses
- formating
- executes tests

The first test was added for the root command

**Pull request merged**
